#!/usr/bin/env bash

# check if git is installed
git --version >/dev/null 2>&1 || aptitude -y install git-core 

git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

curl 'https://raw.github.com/4711/dotfiles/master/vimrc' > ~/.vimrc
curl 'https://raw.github.com/4711/dotfiles/master/.vimrc.local' > ~/.vimrc.local

curl 'https://raw.github.com/4711/dotfiles/master/.bash_aliases' > ~/.bash.aliases

