#!/usr/bin/env bash

################################################################################
# Aliases
################################################################################
curl 'https://raw.github.com/4711/dotfiles/master/.bash_aliases' > ~/.bash.aliases

################################################################################
# Vim
################################################################################

# check if git is installed
git --version >/dev/null 2>&1 || aptitude -y install git-core 

git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

curl 'https://raw.github.com/4711/dotfiles/master/vimrc' > ~/.vimrc
curl 'https://raw.github.com/4711/dotfiles/master/.vimrc.local' > ~/.vimrc.local

# TODO 
# disable colorscheme xoria256

# install bundles
vim -c ':BundleInstall' -c 'qa'

# TODO 
# now we can enable colorscheme xoria256

# TODO 
# check 256 color terminal i.e. TERM=xterm-256color


